version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_store
    ports:
      - "3307:3306"
    networks:
      - springboot_network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - springboot_network
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/book_store
      - spring.datasource.username=root
      - spring.datasource.password=root
    restart: on-failure
networks:
  springboot_network:
    driver: bridge