spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: 'jdbc:tc:mysql:5.7:///book_store?TC_INITSCRIPT=file:src/test/resources/init_database.sql&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=Turkey'

